name: build-action
on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: install node latest code
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: install dependencies
        run: npm i

      - name: build project
        run: npm run build
